version: '3.8'

services:

  database:
    image: postgres:latest 
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgres/data
      # - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}?schema=public
    ports:
      - :5432

  backend:
    build: .  # Build the Docker image using the Dockerfile in the current directory
    environment:
      DATABASE_URL: postgresql://postgres:moehwa32@localhost:5432/test-books-api?schema=public
    ports:
      - "3333:3333"  # Forward the container's port 3333 to the host machine's port 3333 for accessing the backend service
    depends_on:
      - database
    env_file:
      - .env  # Load environment variables from the .env file in the current directory