version: '3.8'

services:

  database:
    image: postgres:latest 
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}  
    ports:
      - :5432

  backend:
    build: . 
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3333:3333"  
    depends_on:
      - database
    env_file:
      - .env 